plugins {
    id 'application'
}

group = 'com.jecs.demos'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()
}

dependencies {
    // Engine modules
    implementation project(':engine-core')
    implementation project(':engine-renderer')
}

// Application configuration
application {
    mainClass = 'com.jecs.demos.rainbow.RainbowDemo'
}

tasks.withType(JavaExec) {
    // Enable Vulkan validation for debugging
    environment 'VK_INSTANCE_LAYERS', 'VK_LAYER_KHRONOS_validation'
    environment 'VK_LAYER_ENABLES', 'VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT'
}
